# Generated by Django 4.2.7 on 2023-11-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='available_doses',
            field=models.IntegerField(default=0, verbose_name='عدد الجرعات المتاحة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccine_type',
            field=models.CharField(choices=[('BCG', 'تطعيم المواليد - بي سي جي'), ('Polio_Newborn', 'تطعيم المواليد - شلل الأطفال'), ('Hexavalent_2Months', 'تطعيم الشهرين - الطعم السداسي'), ('Rotavirus_2Months', 'تطعيم الشهرين - طعم الروتا'), ('Hexavalent_4Months', 'تطعيم الأربعة شهور - الطعم السداسي'), ('Rotavirus_4Months', 'تطعيم الأربعة شهور - طعم الروتا'), ('Hexavalent_6Months', 'تطعيم الستة شهور - الطعم السداسي'), ('Rotavirus_6Months', 'تطعيم الستة شهور - طعم الروتا'), ('Meningococcal_9Months', 'تطعيم التسعة شهور - تطعيمة التهاب السحايا A.C.Y.W135'), ('Polio_9Months', 'تطعيم التسعة شهور - ال'), ('Pneumococcal_1Year', 'تطعيم السنة - طعتطعيمة الوقاية من شلل الأطفم الرئوي 13'), ('Pentavalent_1.5Years', 'تطعيم السنة والنصف - الطعم الخماسي')], default=1, max_length=50, verbose_name='نوع التطعيم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='description',
            field=models.TextField(verbose_name='وصف التطعيم'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='expired_date',
            field=models.DateField(verbose_name='تاريخ انتهاء الصلاحية'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم التطعيم'),
        ),
    ]
